name: Backport


on:
  pull_request_target:
    types: [closed, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  shared:
    uses: Aakvatech-Limited/frappe-maintenance/.github/workflows/backport-reusable.yml@stable
