name: No Raw SQL


on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shared:
    uses: Aakvatech-Limited/frappe-maintenance/.github/workflows/no-raw-sql-reusable.yml@stable
