name: Pre-commit


on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  shared:
    uses: Aakvatech-Limited/frappe-maintenance/.github/workflows/pre-commit-reusable.yml@stable
