name: Tag and promote from PR label


on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: write
  issues: write
  pull-requests: read

jobs:
  shared:
    uses: Aakvatech-Limited/frappe-maintenance/.github/workflows/tag-and-promote-from-pr-label-reusable.yml@stable
