name: Label Failed Pull Requests


on:
  workflow_run:
    workflows: ["*", "!Label Failed Pull Requests"]
    types: [completed]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pull-requests: write
  issues: write

jobs:
  shared:
    uses: Aakvatech-Limited/frappe-maintenance/.github/workflows/label-failed-prs-reusable.yml@stable
